import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { auth } from "@/lib/auth"; import { redirect } from "@/i18n/navigation"; import { db } from "@/lib/db";
import { DashboardShell } from "@/components/dashboard/DashboardShell"; import { adminNavItems } from "@/lib/adminNav"; import { PermissionMatrix } from "@/components/admin/PermissionMatrix"; import { PromoteAdminDialog } from "@/components/admin/PromoteAdminDialog";
import { updateAdminPermissionsAction, suspendAdminAction, reactivateAdminAction } from "@/lib/actions/adminManagement";
export default async function AdminDetail({ params }: { params: Promise<{ locale: string; adminId: string }> }) {
 const { locale, adminId }=await params; setRequestLocale(locale); const session=await auth(); if(session?.user.role!=="SUPER_ADMIN"){redirect({href:"/admin",locale});return}
 const [t,tNav]=await Promise.all([getTranslations({locale,namespace:"adminManagement.detail"}),getTranslations({locale,namespace:"dashboard.nav"})]);
 const user=await db.user.findUnique({where:{id:adminId},select:{id:true,name:true,email:true,role:true,deactivatedAt:true,adminPermissions:{select:{permission:true}},auditLogs:{select:{action:true,createdAt:true},orderBy:{createdAt:"desc"},take:20}}}); if(!user||!["ADMIN","SUPER_ADMIN"].includes(user.role))notFound();
 async function update(formData:FormData){"use server";await updateAdminPermissionsAction(user!.id,undefined,formData)}
 return <DashboardShell navItems={await adminNavItems(tNav, session.user)} userName={session.user.name??""}><h1 className="text-3xl font-extrabold">{user.name}</h1><p>{user.email}</p><form action={update} className="mt-8 space-y-4"><PermissionMatrix selected={user.adminPermissions.map(p=>p.permission)} disabled={user.role==="SUPER_ADMIN"||user.id===session.user.id}/><button disabled={user.role==="SUPER_ADMIN"||user.id===session.user.id} className="min-h-11 rounded-md bg-blue px-5 font-bold text-white">{t("savePermissions")}</button></form>{user.role==="ADMIN"&&user.id!==session.user.id&&<form action={user.deactivatedAt?reactivateAdminAction.bind(null,user.id):suspendAdminAction.bind(null,user.id)} className="mt-5"><button className="min-h-11 rounded-md border px-5 font-bold">{user.deactivatedAt?t("reactivate"):t("suspend")}</button></form>}{user.role==="ADMIN"&&!user.deactivatedAt&&<PromoteAdminDialog adminId={user.id}/>}<section className="mt-8"><h2 className="text-xl font-bold">{t("activity")}</h2>{user.auditLogs.map((a,i)=><p key={i} className="border-b py-2">{a.action} · {new Intl.DateTimeFormat(locale,{dateStyle:"medium",timeStyle:"short"}).format(a.createdAt)}</p>)}</section></DashboardShell>
}
