import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { auth } from "@/lib/auth"; import { redirect } from "@/i18n/navigation"; import { db } from "@/lib/db";
import { DashboardShell } from "@/components/dashboard/DashboardShell"; import { PageHeader } from "@/components/ui/PageHeader"; import { Surface } from "@/components/ui/Surface"; import { Badge } from "@/components/ui/Badge"; import { adminNavItems } from "@/lib/adminNav";
export default async function AdminStudentDetailPage({ params }: { params: Promise<{ locale: string; id: string }> }) {
  const { locale, id } = await params; setRequestLocale(locale); const session = await auth(); const user = session?.user;
  if (!user || !["ADMIN", "SUPER_ADMIN"].includes(user.role)) { redirect({ href: "/login", locale }); return; }
  const t = await getTranslations({ locale, namespace: "admin.operations.studentDetail" }); const tNav = await getTranslations({ locale, namespace: "dashboard.nav" }); const tSubjects = await getTranslations({ locale, namespace: "subjects.items" }); const tLevels = await getTranslations({ locale, namespace: "gradeLevels" });
  const student = await db.studentProfile.findUnique({ where: { id }, include: { user: { select: { name: true, email: true, deactivatedAt: true } }, academicLevel: true, learningGoals: { include: { subject: true } }, parentRelationships: { include: { parentProfile: { include: { user: { select: { name: true, email: true } } } } } }, bookings: { orderBy: { startAt: "desc" }, take: 10, include: { tutorProfile: { include: { user: { select: { name: true } } } }, subject: true, session: { select: { status: true } } } } } }); if (!student) notFound();
  return <DashboardShell navItems={await adminNavItems(tNav, user)} userName={user.name ?? ""}><PageHeader title={`${student.firstName} ${student.lastName}`} description={student.user?.email ?? t("noLogin")} status={<Badge variant="neutral">{t(student.managementMode === "SELF_MANAGED" ? "selfManaged" : "guardianManaged")}</Badge>} />
    <div className="mt-6 grid gap-5 lg:grid-cols-2"><Surface><h2 className="font-extrabold">{t("academic")}</h2><dl className="mt-4 space-y-2 text-sm"><div><dt className="font-bold">{t("level")}</dt><dd>{student.academicLevel ? tLevels(student.academicLevel.slug) : t("notProvided")}</dd></div><div><dt className="font-bold">{t("location")}</dt><dd>{[student.city, student.province].filter(Boolean).join(", ") || t("notProvided")}</dd></div><div><dt className="font-bold">{t("mode")}</dt><dd>{student.tutoringMode}</dd></div></dl></Surface><Surface><h2 className="font-extrabold">{t("guardians")}</h2>{student.parentRelationships.length ? <ul className="mt-4 space-y-2">{student.parentRelationships.map((r) => <li key={r.id} className="text-sm"><span className="font-bold">{r.parentProfile.user.name ?? r.parentProfile.user.email}</span> · {r.status}</li>)}</ul> : <p className="mt-4 text-sm text-text-secondary">{t("noGuardians")}</p>}</Surface></div>
    <Surface className="mt-5"><h2 className="font-extrabold">{t("goals")}</h2>{student.learningGoals.length ? <ul className="mt-4 space-y-2">{student.learningGoals.map((g) => <li key={g.id} className="text-sm">{g.subject ? <Badge variant="neutral">{tSubjects(g.subject.slug)}</Badge> : null} <span className="ml-2">{g.description}</span></li>)}</ul> : <p className="mt-3 text-sm text-text-secondary">{t("noGoals")}</p>}</Surface>
    <Surface className="mt-5"><h2 className="font-extrabold">{t("recentBookings")}</h2>{student.bookings.length ? <div className="mt-4 space-y-3">{student.bookings.map((b) => <div key={b.id} className="rounded-lg border border-border p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><span className="font-bold">{tSubjects(b.subject.slug)} · {b.tutorProfile.user.name}</span><span>{b.status} / {b.session?.status ?? "—"}</span></div><p className="mt-1 text-text-secondary">{new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: b.timezone }).format(b.startAt)}</p></div>)}</div> : <p className="mt-3 text-sm text-text-secondary">{t("noBookings")}</p>}</Surface>
  </DashboardShell>;
}
