import type { LegalDocumentContent } from "./types";

/** FG-LEGAL1B — traduction française complète et substantiellement
 * équivalente de la Politique de confidentialité approuvée. Correspond
 * section par section à privacyContent.en.ts. */

export const privacyContentFr: LegalDocumentContent = {
  effectiveDate: "30 août 2026",
  lastUpdated: "30 août 2026",
  sections: [
    {
      number: 1,
      heading: "Objet de la présente Politique de confidentialité",
      blocks: [
        {
          type: "p",
          text: "FutureTutor est une place de marché de tutorat détenue et exploitée par FYRA SERVICES INC., une société constituée sous le régime fédéral au Canada.",
        },
        {
          type: "p",
          text: "La présente Politique de confidentialité explique comment FYRA SERVICES INC., exerçant ses activités sous le nom de FutureTutor (« FutureTutor », « nous », « notre » ou « nos »), recueille, utilise, divulgue, conserve, protège et traite autrement les renseignements personnels lorsque des personnes utilisent le site Web, l'application Web, l'application Web progressive, la place de marché de tutorat, la classe virtuelle et les services connexes de FutureTutor (collectivement, la « Plateforme »).",
        },
        {
          type: "p",
          text: "La présente Politique de confidentialité doit être lue conjointement avec nos Conditions d'utilisation et tout avis supplémentaire fourni au moment de la collecte des renseignements personnels.",
        },
        {
          type: "p",
          text: "FutureTutor met en relation des Élèves, des Parents ou tuteurs légaux, et des Tuteurs pour du tutorat en ligne et en personne.",
        },
        { type: "p", text: "L'exploitation de la Plateforme nous oblige à traiter des renseignements personnels à des fins telles que :" },
        {
          type: "ul",
          items: [
            "la création de compte;",
            "la vérification des Tuteurs;",
            "l'autorisation des Parents et Tuteurs;",
            "les demandes de tutorat;",
            "le jumelage avec un Tuteur;",
            "les réservations;",
            "les paiements;",
            "le tutorat virtuel;",
            "le tutorat en personne;",
            "le soutien à la clientèle;",
            "la sécurité;",
            "la prévention de la fraude;",
            "la gestion de la qualité;",
            "la conformité juridique; et",
            "l'administration de la Plateforme.",
          ],
        },
        {
          type: "p",
          text: "Nous nous engageons à ne recueillir et à n'utiliser des renseignements personnels qu'aux fins qu'une personne raisonnable jugerait appropriées dans les circonstances, conformément à la loi canadienne applicable en matière de protection de la vie privée.",
        },
        {
          type: "p",
          text: "La LPRPDE exige généralement que les organisations du secteur privé recueillent, utilisent et divulguent les renseignements personnels par des moyens justes et licites, avec le consentement requis, et uniquement à des fins déterminées et raisonnables.",
        },
      ],
    },
    {
      number: 2,
      heading: "Organisation responsable de vos renseignements personnels",
      partTitle: "Partie I — Responsabilisation",
      blocks: [
        { type: "p", text: "L'organisation responsable des renseignements personnels traités par l'entremise de FutureTutor est :" },
        { type: "p", text: "FYRA SERVICES INC." },
        { type: "p", text: "FutureTutor est un nom commercial et une Plateforme exploités par FYRA SERVICES INC." },
        { type: "p", text: "La personne désignée pour superviser les pratiques de confidentialité de FutureTutor peut être jointe à :" },
        { type: "p", text: "legal@futuretutor.ca" },
        {
          type: "p",
          text: "FutureTutor peut désigner du personnel ou des fournisseurs de services supplémentaires pour l'aider à répondre aux demandes relatives à la protection des renseignements personnels, mais FYRA SERVICES INC. demeure responsable de ses obligations en vertu de la loi applicable.",
        },
      ],
    },
    {
      number: 3,
      heading: "Lois sur la protection de la vie privée",
      blocks: [
        { type: "p", text: "Selon les circonstances, le traitement des renseignements personnels par FutureTutor peut être assujetti à des lois sur la protection de la vie privée, notamment :" },
        {
          type: "ul",
          items: [
            "la Loi sur la protection des renseignements personnels et les documents électroniques (LPRPDE);",
            "la Personal Information Protection Act de l'Alberta (PIPA);",
            "la Loi sur la protection des renseignements personnels dans le secteur privé du Québec;",
            "et toute autre loi provinciale ou fédérale applicable en matière de protection de la vie privée.",
          ],
        },
        { type: "p", text: "La PIPA de l'Alberta est la loi sur la protection de la vie privée du secteur privé applicable aux organisations du secteur privé réglementées par la province en Alberta." },
        { type: "p", text: "La LPRPDE peut s'appliquer aux activités commerciales et, en particulier, aux transferts interprovinciaux ou internationaux de renseignements personnels, le cas échéant." },
        { type: "p", text: "Rien dans la présente Politique n'a pour objet de réduire les droits que la loi applicable vous confère." },
      ],
    },
    {
      number: 4,
      heading: "Renseignements que vous fournissez directement",
      partTitle: "Partie II — Renseignements que nous recueillons",
      blocks: [
        { type: "p", text: "Nous pouvons recueillir des renseignements que vous fournissez directement à FutureTutor." },
        { type: "p", text: "Selon votre rôle, cela peut inclure :" },
        {
          type: "p",
          text: "Renseignements d'identité — prénom; nom de famille; nom préféré; date de naissance ou âge, lorsque requis; rôle du compte; renseignements liés à l'identité; photographie de profil, si fournie; autres renseignements raisonnablement nécessaires pour identifier ou gérer votre compte.",
        },
        {
          type: "p",
          text: "Renseignements de contact — adresse courriel; numéro de téléphone; adresse postale; ville; province; code postal; pays.",
        },
        {
          type: "p",
          text: "Renseignements de compte — identifiants de connexion; statut du compte; renseignements de création de compte; préférence linguistique; rôle du compte; renseignements d'authentification et de sécurité.",
        },
        { type: "p", text: "Les mots de passe sont destinés à être stockés au moyen de techniques cryptographiques sécurisées plutôt qu'en clair." },
      ],
    },
    {
      number: 5,
      heading: "Renseignements sur les Élèves",
      blocks: [
        { type: "p", text: "Pour les Élèves, nous pouvons recueillir des renseignements incluant :" },
        {
          type: "ul",
          items: [
            "le nom;",
            "l'âge ou la date de naissance;",
            "l'année scolaire ou le niveau scolaire;",
            "les renseignements sur l'établissement scolaire;",
            "les matières;",
            "les domaines pour lesquels du tutorat est demandé;",
            "le niveau de difficulté autoévalué;",
            "les préférences de tutorat;",
            "la disponibilité;",
            "le mode de tutorat préféré;",
            "les objectifs d'apprentissage;",
            "les notes de la demande de tutorat;",
            "l'historique de tutorat antérieur sur FutureTutor;",
            "la présence aux séances;",
            "l'historique des réservations;",
            "les commentaires et évaluations;",
            "les renseignements opérationnels sur la fiabilité;",
            "la relation avec un Parent ou Tuteur;",
            "d'autres renseignements nécessaires à la prestation des services de tutorat.",
          ],
        },
        { type: "p", text: "FutureTutor n'entend pas faire des cotes opérationnelles de l'Élève des évaluations de l'intelligence, de l'aptitude, de la personnalité ou de la capacité scolaire intrinsèque." },
      ],
    },
    {
      number: 6,
      heading: "Renseignements sur les Parents et Tuteurs",
      blocks: [
        { type: "p", text: "Nous pouvons recueillir des renseignements sur les Parents et Tuteurs légaux, notamment :" },
        {
          type: "ul",
          items: [
            "les renseignements d'identité;",
            "les coordonnées;",
            "la relation avec un Élève;",
            "l'autorisation du compte;",
            "les profils d'Élève liés;",
            "les dossiers de consentement;",
            "les renseignements relatifs au paiement;",
            "les demandes de tutorat;",
            "l'historique des réservations;",
            "les communications;",
            "les permissions du compte;",
            "les invitations de Tuteur et le statut de la relation.",
          ],
        },
        { type: "p", text: "Lorsque plusieurs Parents ou Tuteurs sont liés à un Élève, nous pouvons conserver des dossiers indiquant qui a été autorisé à gérer cet Élève." },
      ],
    },
    {
      number: 7,
      heading: "Renseignements concernant les mineurs",
      blocks: [
        { type: "p", text: "FutureTutor peut fournir des services de tutorat à des enfants et à des adolescents." },
        { type: "p", text: "Nous reconnaissons que les renseignements personnels concernant les enfants et les jeunes exigent une attention accrue." },
        { type: "p", text: "Lorsqu'un enfant ne peut fournir un consentement significatif de façon autonome, FutureTutor exige le consentement ou l'autorisation appropriés d'un Parent ou Tuteur légal." },
        {
          type: "p",
          text: "Les autorités canadiennes de protection de la vie privée ont indiqué que les organisations devraient accorder une attention particulière à la vie privée des enfants, et le Commissariat à la protection de la vie privée du Canada considère généralement que les enfants de moins de 13 ans sont peu susceptibles de pouvoir consentir de façon significative de manière autonome, sauf circonstances inhabituelles.",
        },
        { type: "p", text: "Par conséquent, les enfants de moins de 13 ans qui utilisent FutureTutor doivent généralement le faire par l'entremise d'un Parent ou Tuteur légal autorisé." },
        { type: "p", text: "FutureTutor peut également restreindre la capacité des mineurs à, de façon autonome :" },
        {
          type: "ul",
          items: [
            "effectuer des paiements;",
            "fournir ou modifier des adresses privées;",
            "créer certaines réservations;",
            "gérer des paramètres financiers;",
            "modifier des relations de tuteur;",
            "exercer d'autres permissions sensibles du compte.",
          ],
        },
        { type: "p", text: "Les Parents et Tuteurs ne devraient fournir que les renseignements raisonnablement nécessaires au tutorat." },
      ],
    },
    {
      number: 8,
      heading: "Renseignements sur les Tuteurs",
      blocks: [
        { type: "p", text: "Nous pouvons recueillir des renseignements substantiels auprès des personnes qui présentent leur candidature pour devenir Tuteur." },
        { type: "p", text: "Cela peut inclure :" },
        {
          type: "p",
          text: "Renseignements de profil — nom; coordonnées; photographie; biographie; langues; matières enseignées; formation; qualifications; expérience; disponibilité; mode de tutorat; zone de service.",
        },
        { type: "p", text: "Vérification scolaire et professionnelle — nous pouvons recueillir :" },
        {
          type: "ul",
          items: ["des diplômes;", "des relevés de notes;", "des certificats;", "des dossiers scolaires;", "des qualifications professionnelles;", "des documents justificatifs;", "les établissements émetteurs;", "les résultats de vérification."],
        },
        { type: "p", text: "Renseignements d'évaluation du Tuteur — FutureTutor peut également recueillir ou générer :" },
        {
          type: "ul",
          items: [
            "les résultats d'entrevue;",
            "les notes d'entrevue;",
            "les résultats d'évaluation;",
            "les renseignements sur l'achèvement de la formation;",
            "les résultats d'examen;",
            "les résultats d'évaluation par matière;",
            "le statut de vérification;",
            "le statut d'approbation;",
            "les renseignements d'examen de la qualité;",
            "les renseignements sur la performance du Tuteur.",
          ],
        },
        { type: "p", text: "Renseignements de paiement et de versement — nous ou notre fournisseur de paiement pouvons traiter :" },
        {
          type: "ul",
          items: [
            "les renseignements du compte de versement;",
            "les identifiants de compte connecté Stripe;",
            "le statut du paiement;",
            "les renseignements de transaction;",
            "les montants versés;",
            "les renseignements fiscaux, lorsque requis;",
            "d'autres renseignements financiers nécessaires à l'administration des paiements aux Tuteurs.",
          ],
        },
        { type: "p", text: "Les renseignements bancaires ou de carte complets peuvent être recueillis directement par les processeurs de paiement plutôt que par FutureTutor." },
      ],
    },
    {
      number: 9,
      heading: "Cotes et évaluations des Tuteurs",
      blocks: [
        { type: "p", text: "FutureTutor peut maintenir :" },
        { type: "p", text: "Cotes publiques du Tuteur — celles-ci peuvent être fondées sur des commentaires légitimes fournis après des séances admissibles." },
        {
          type: "p",
          text: "Cotes internes du Tuteur — FutureTutor peut générer des évaluations opérationnelles privées fondées sur des renseignements tels que les qualifications, la vérification, la formation, les résultats d'examen, la fiabilité, la présence, les annulations, l'expérience du Tuteur, l'historique de tutorat, les commentaires des utilisateurs et les mesures de qualité de la Plateforme.",
        },
        { type: "p", text: "Ces cotes internes visent à soutenir les activités de la Plateforme et la qualité de la place de marché." },
        { type: "p", text: "FutureTutor peut également associer des niveaux de confiance ou des renseignements de version aux cotes internes." },
      ],
    },
    {
      number: 10,
      heading: "Renseignements sur la fiabilité de l'Élève",
      blocks: [
        { type: "p", text: "FutureTutor peut maintenir une cote interne de fiabilité de l'Élève ou une mesure opérationnelle similaire." },
        {
          type: "p",
          text: "Ces renseignements peuvent être fondés sur des facteurs tels que la présence, les annulations, les absences, la conduite relative aux réservations, l'historique des séances et les commentaires du Tuteur concernant la fiabilité opérationnelle.",
        },
        { type: "p", text: "Cette cote est : privée; opérationnelle; non destinée à évaluer l'intelligence; non destinée à évaluer le potentiel scolaire; non destinée à diagnostiquer une condition quelconque." },
        { type: "p", text: "FutureTutor n'utilise pas actuellement la cote de fiabilité de l'Élève comme facteur direct de tarification client." },
      ],
    },
    {
      number: 11,
      heading: "Renseignements relatifs à la demande de tutorat",
      partTitle: "Partie III — Demandes de tutorat et jumelage",
      blocks: [
        { type: "p", text: "Lorsque du tutorat est demandé, nous pouvons recueillir :" },
        {
          type: "ul",
          items: ["la matière;", "le niveau scolaire;", "la date;", "l'heure;", "la durée;", "le mode de tutorat;", "les objectifs d'apprentissage;", "les chapitres ou concepts à réviser;", "des notes supplémentaires;", "les préférences linguistiques;", "la disponibilité;", "le lieu, le cas échéant."],
        },
      ],
    },
    {
      number: 12,
      heading: "Renseignements relatifs au jumelage",
      blocks: [
        { type: "p", text: "FutureTutor utilise les renseignements de la Plateforme afin d'identifier les Tuteurs appropriés pour les demandes de tutorat." },
        { type: "p", text: "Le jumelage peut tenir compte de renseignements tels que :" },
        {
          type: "ul",
          items: [
            "le statut d'approbation du Tuteur;",
            "les matières;",
            "le niveau scolaire;",
            "la disponibilité;",
            "le mode de tutorat;",
            "la langue;",
            "les engagements d'horaire existants;",
            "les relations de tutorat antérieures;",
            "les indicateurs de qualité du Tuteur;",
            "les renseignements géographiques approximatifs;",
            "la disponibilité de la place de marché;",
            "d'autres facteurs de jumelage légitimes.",
          ],
        },
        { type: "p", text: "FutureTutor peut générer une cote de jumelage ou un classement propre à une demande." },
        { type: "p", text: "Les cotes de jumelage sont des outils opérationnels et ne garantissent ni résultats scolaires ni compatibilité personnelle." },
      ],
    },
    {
      number: 13,
      heading: "Renseignements de localisation",
      partTitle: "Partie IV — Tutorat en personne et confidentialité du lieu",
      blocks: [
        { type: "p", text: "Lorsqu'une séance de tutorat en personne est demandée, FutureTutor peut recueillir un lieu de tutorat exact." },
        { type: "p", text: "Cela peut inclure :" },
        { type: "ul", items: ["l'adresse municipale;", "le numéro d'unité ou d'appartement;", "la ville;", "la province;", "le code postal;", "des instructions d'arrivée facultatives."] },
        { type: "p", text: "FutureTutor n'exige actuellement pas de suivi GPS continu pour offrir les fonctionnalités habituelles de tutorat en personne." },
        { type: "p", text: "Si une géolocalisation fondée sur l'appareil est introduite ultérieurement, FutureTutor fournira un avis approprié et obtiendra le consentement requis avant de l'utiliser." },
      ],
    },
    {
      number: 14,
      heading: "Confidentialité du lieu pendant le jumelage",
      blocks: [
        { type: "p", text: "FutureTutor est conçue pour limiter la divulgation des adresses privées exactes pendant le jumelage ouvert de Tuteurs." },
        { type: "p", text: "Avant la confirmation d'une Réservation, les Tuteurs potentiels peuvent ne recevoir que des renseignements de localisation limités ou approximatifs, tels que :" },
        { type: "ul", items: ["la ville;", "la province;", "le quartier ou la zone approximative;", "des renseignements géographiques partiels."] },
        { type: "p", text: "L'adresse privée exacte du tutorat ne devrait pas être divulguée à chaque Tuteur qui reçoit une occasion de jumelage." },
      ],
    },
    {
      number: 15,
      heading: "Divulgation de l'adresse exacte",
      blocks: [
        { type: "p", text: "Une fois qu'un Tuteur a été sélectionné et que la Réservation est confirmée de façon faisant autorité, FutureTutor peut divulguer le lieu exact du tutorat au Tuteur assigné à cette Réservation." },
        { type: "p", text: "Ce Tuteur peut également recevoir les instructions d'arrivée applicables." },
        { type: "p", text: "Cette divulgation vise à permettre au Tuteur confirmé d'exécuter le service de tutorat demandé." },
        { type: "p", text: "FutureTutor restreint l'accès aux renseignements de localisation selon le rôle et le statut de la Réservation." },
      ],
    },
    {
      number: 16,
      heading: "Instructions d'arrivée",
      blocks: [
        { type: "p", text: "Les instructions d'arrivée peuvent contenir des détails privés nécessaires pour localiser ou accéder au lieu de tutorat." },
        { type: "p", text: "Les utilisateurs ne devraient pas inclure de renseignements sensibles qui ne sont pas nécessaires à la séance de tutorat." },
        { type: "p", text: "FutureTutor traite les instructions d'arrivée comme des renseignements privés liés à la Réservation." },
      ],
    },
    {
      number: 17,
      heading: "Renseignements sur la classe virtuelle",
      partTitle: "Partie V — Tutorat en ligne",
      blocks: [
        { type: "p", text: "FutureTutor offre du tutorat en ligne par l'entremise d'une classe virtuelle intégrée." },
        { type: "p", text: "Pour y participer, la Plateforme peut traiter des renseignements relatifs :" },
        {
          type: "ul",
          items: [
            "à l'identité du participant;",
            "au rôle;",
            "à la Réservation;",
            "à la séance;",
            "à la connexion vidéo;",
            "à l'état du microphone;",
            "à l'état de la caméra;",
            "au partage d'écran;",
            "à l'état de participation;",
            "aux événements de connexion;",
            "à la minuterie de séance.",
          ],
        },
        { type: "p", text: "FutureTutor utilise actuellement Daily comme fournisseur technologique pour les fonctionnalités de la classe virtuelle." },
      ],
    },
    {
      number: 18,
      heading: "Caméra et microphone",
      blocks: [
        { type: "p", text: "L'accès à la caméra et au microphone requiert une autorisation de l'appareil ou du navigateur de l'utilisateur." },
        { type: "p", text: "FutureTutor n'active pas d'autorisations d'appareil au-delà des capacités permises par le navigateur ou le système d'exploitation applicable." },
        { type: "p", text: "Les utilisateurs peuvent contrôler leur caméra et leur microphone pendant les séances de tutorat, sous réserve des fonctionnalités de la Plateforme." },
      ],
    },
    {
      number: 19,
      heading: "Partage d'écran",
      blocks: [
        { type: "p", text: "Les Élèves et les Tuteurs peuvent choisir de partager leur écran pendant une séance en classe virtuelle." },
        { type: "p", text: "Le partage d'écran peut exposer des renseignements visibles sur l'écran de l'utilisateur." },
        { type: "p", text: "Les utilisateurs sont responsables de fermer tout contenu privé ou non nécessaire avant de partager leur écran." },
      ],
    },
    {
      number: 20,
      heading: "Enregistrement",
      blocks: [
        { type: "p", text: "FutureTutor ne fournit actuellement pas d'enregistrement systématique des séances en classe virtuelle." },
        { type: "p", text: "FutureTutor n'entend pas enregistrer les séances de tutorat standard sans avis approprié et sans le consentement requis par la loi." },
        { type: "p", text: "Si une fonctionnalité d'enregistrement est introduite ultérieurement, la présente Politique de confidentialité et les avis pertinents seront mis à jour avant l'activation de l'enregistrement." },
      ],
    },
    {
      number: 21,
      heading: "Observateurs Parent ou Tuteur",
      blocks: [
        { type: "p", text: "Lorsque cela est activé, un Parent ou Tuteur autorisé peut se joindre à certaines séances en classe virtuelle à titre d'observateur." },
        { type: "p", text: "Les permissions de l'observateur peuvent être techniquement restreintes." },
        { type: "p", text: "Les renseignements de participation associés à un observateur peuvent être traités afin de gérer l'accès autorisé et la sécurité de la séance." },
      ],
    },
    {
      number: 22,
      heading: "Renseignements sur la Réservation",
      partTitle: "Partie VI — Réservations et renseignements de séance",
      blocks: [
        { type: "p", text: "Nous pouvons recueillir des renseignements relatifs :" },
        {
          type: "ul",
          items: [
            "à la demande de tutorat;",
            "au Tuteur jumelé;",
            "à l'Élève;",
            "au Parent ou Tuteur;",
            "à la date et l'heure prévues;",
            "au mode de tutorat;",
            "au prix;",
            "au versement au Tuteur;",
            "à l'état du paiement;",
            "au statut de la Réservation;",
            "aux annulations;",
            "aux remboursements;",
            "à l'achèvement de la séance;",
            "à l'instantané du lieu pour les séances en personne.",
          ],
        },
        { type: "p", text: "Certains renseignements de Réservation sont conservés à titre de dossier historique de la transaction." },
      ],
    },
    {
      number: 23,
      heading: "Présence et enregistrement de présence",
      blocks: [
        { type: "p", text: "FutureTutor peut enregistrer :" },
        { type: "ul", items: ["l'enregistrement de présence du Tuteur;", "l'enregistrement de présence de l'Élève;", "les horodatages;", "le début de la séance;", "l'achèvement de la séance;", "le statut d'absence;", "les événements pertinents du cycle de vie de la séance."] },
        { type: "p", text: "Nous utilisons ces renseignements à des fins telles que :" },
        { type: "ul", items: ["l'administration des séances de tutorat;", "le règlement des différends;", "l'application des règles d'annulation;", "la détermination des versements aux Tuteurs;", "le traitement des absences;", "le maintien de la fiabilité de la Plateforme."] },
      ],
    },
    {
      number: 24,
      heading: "Paiements des clients",
      partTitle: "Partie VII — Paiements",
      blocks: [
        { type: "p", text: "FutureTutor utilise des fournisseurs de paiement tiers, incluant actuellement Stripe, pour traiter les paiements." },
        { type: "p", text: "Les renseignements de paiement traités peuvent inclure :" },
        {
          type: "ul",
          items: [
            "le nom du client;",
            "les renseignements de facturation;",
            "le montant de la transaction;",
            "l'autorisation de paiement;",
            "les identifiants de PaymentIntent;",
            "le statut du paiement;",
            "les remboursements;",
            "les métadonnées du mode de paiement;",
            "d'autres renseignements relatifs à la transaction.",
          ],
        },
        { type: "p", text: "Les renseignements de carte de paiement peuvent être soumis directement à Stripe et peuvent ne pas être stockés en entier par FutureTutor." },
      ],
    },
    {
      number: 25,
      heading: "Versements aux Tuteurs",
      blocks: [
        { type: "p", text: "FutureTutor peut utiliser Stripe Connect ou une infrastructure de paiement connexe pour administrer les versements aux Tuteurs." },
        { type: "p", text: "Les renseignements relatifs aux versements aux Tuteurs peuvent inclure :" },
        {
          type: "ul",
          items: ["les identifiants de compte du Tuteur;", "les identifiants de compte connecté;", "le statut du versement;", "le montant du versement;", "l'historique des paiements;", "les renseignements fiscaux ou d'identité requis par Stripe ou la loi applicable."],
        },
        { type: "p", text: "Stripe peut recueillir de façon indépendante les renseignements nécessaires pour vérifier les comptes connectés." },
      ],
    },
    {
      number: 26,
      heading: "Renseignements sur la tarification client",
      blocks: [
        { type: "p", text: "FutureTutor peut créer et conserver des dossiers concernant :" },
        { type: "ul", items: ["le prix client;", "les composantes de tarification;", "les ajustements applicables;", "les taxes;", "la règle ou la version de tarification;", "l'instantané de tarification propre à la réservation."] },
        { type: "p", text: "Ces renseignements sont utilisés pour maintenir l'intégrité des transactions et régler les différends." },
      ],
    },
    {
      number: 27,
      heading: "Renseignements sur la rémunération du Tuteur",
      blocks: [
        { type: "p", text: "FutureTutor peut conserver des dossiers concernant :" },
        { type: "ul", items: ["le versement au Tuteur;", "les règles de versement;", "les incitatifs;", "les considérations de déplacement;", "les qualifications ou le palier pertinents au versement;", "l'instantané de versement propre à la réservation."] },
        { type: "p", text: "Le prix client et le versement au Tuteur sont calculés de façon indépendante." },
      ],
    },
    {
      number: 28,
      heading: "Fins de la collecte et de l'utilisation",
      partTitle: "Partie VIII — Comment nous utilisons les renseignements personnels",
      blocks: [
        { type: "p", text: "FutureTutor peut utiliser des renseignements personnels afin de :" },
        {
          type: "ul",
          items: [
            "créer et authentifier des comptes;",
            "tenir à jour les profils d'utilisateur;",
            "vérifier l'identité;",
            "vérifier les qualifications des Tuteurs;",
            "administrer les entrevues et évaluations des Tuteurs;",
            "approuver ou rejeter les candidatures de Tuteur;",
            "gérer les relations Élève et Parent;",
            "obtenir l'autorisation du Tuteur légal;",
            "fournir du tutorat;",
            "jumeler les Élèves avec des Tuteurs;",
            "gérer le Jumelage rapide;",
            "créer des Réservations;",
            "traiter les paiements;",
            "traiter les versements aux Tuteurs;",
            "administrer les annulations et remboursements;",
            "fournir les fonctionnalités de la classe virtuelle;",
            "gérer le tutorat en personne;",
            "divulguer les adresses de tutorat confirmées aux Tuteurs autorisés;",
            "gérer la présence;",
            "détecter les absences;",
            "fournir un soutien à la clientèle;",
            "communiquer des renseignements sur le service;",
            "maintenir la sécurité de la Plateforme;",
            "détecter la fraude ou les abus;",
            "faire respecter les Conditions;",
            "régler les différends;",
            "améliorer la fiabilité;",
            "résoudre les problèmes techniques;",
            "maintenir la sécurité;",
            "satisfaire aux exigences fiscales, comptables et réglementaires;",
            "se conformer à la loi applicable.",
          ],
        },
      ],
    },
    {
      number: 29,
      heading: "Consentement",
      blocks: [
        { type: "p", text: "Lorsque le consentement est requis, FutureTutor cherche à obtenir un consentement significatif et approprié à la sensibilité des renseignements et aux circonstances." },
        {
          type: "p",
          text: "Les orientations canadiennes en matière de protection de la vie privée soulignent que les personnes devraient comprendre des éléments clés tels que les renseignements personnels recueillis, les fins pour lesquelles ils seront utilisés, les parties à qui ils peuvent être divulgués, et les risques ou conséquences importants.",
        },
        { type: "p", text: "Le consentement peut être :" },
        { type: "ul", items: ["exprès;", "implicite, lorsque la loi le permet;", "fourni par un Parent ou Tuteur autorisé;", "autrement obtenu conformément à la loi applicable."] },
        { type: "p", text: "Certains traitements peuvent être permis ou requis sans consentement en vertu de la loi applicable." },
      ],
    },
    {
      number: 30,
      heading: "Retrait du consentement",
      blocks: [
        { type: "p", text: "Lorsque le traitement est fondé sur le consentement, vous pouvez retirer votre consentement, sous réserve :" },
        { type: "ul", items: ["des restrictions légales;", "des exigences contractuelles;", "d'un préavis raisonnable;", "des renseignements que FutureTutor doit conserver pour mener à terme des transactions existantes ou se conformer à la loi."] },
        { type: "p", text: "Le retrait peut empêcher FutureTutor de continuer à fournir certaines fonctions de la Plateforme." },
        { type: "p", text: "FutureTutor expliquera les conséquences importantes du retrait, le cas échéant." },
      ],
    },
    {
      number: 31,
      heading: "Autres utilisateurs de la Plateforme",
      partTitle: "Partie IX — Divulgation des renseignements personnels",
      blocks: [
        { type: "p", text: "FutureTutor peut divulguer des renseignements personnels limités entre les participants de la Plateforme lorsque cela est nécessaire pour faciliter le tutorat." },
        { type: "p", text: "Par exemple :" },
        {
          type: "p",
          text: "Un Élève ou un Parent peut recevoir le nom du Tuteur; son profil; ses qualifications; ses évaluations; sa disponibilité pertinente; d'autres renseignements destinés à aider à sélectionner ou identifier le Tuteur.",
        },
        {
          type: "p",
          text: "Un Tuteur potentiel peut recevoir la matière du tutorat; le niveau scolaire; la date/l'heure demandée; le mode de tutorat; le lieu approximatif, le cas échéant; des renseignements limités raisonnablement nécessaires pour évaluer la demande.",
        },
        {
          type: "p",
          text: "Un Tuteur confirmé peut recevoir les renseignements sur l'Élève raisonnablement nécessaires pour offrir le tutorat; les détails confirmés de la séance; l'adresse exacte du tutorat en personne, le cas échéant; les instructions d'arrivée, le cas échéant.",
        },
        { type: "p", text: "FutureTutor cherche à limiter les divulgations à ce qui est raisonnablement nécessaire à la transaction." },
      ],
    },
    {
      number: 32,
      heading: "Fournisseurs de services",
      blocks: [
        { type: "p", text: "FutureTutor peut divulguer des renseignements personnels à des fournisseurs de services qui exécutent des services en notre nom." },
        { type: "p", text: "Ces fournisseurs peuvent inclure des entreprises offrant :" },
        { type: "ul", items: ["l'infrastructure infonuagique;", "l'hébergement de bases de données;", "les paiements;", "les communications vidéo;", "l'envoi de courriels;", "l'hébergement d'applications;", "la journalisation;", "la sécurité;", "le soutien technique."] },
        { type: "p", text: "Les fournisseurs actuellement connus utilisés par FutureTutor incluent :" },
        {
          type: "ul",
          items: [
            "Stripe — traitement des paiements et infrastructure de versement aux Tuteurs;",
            "Daily — infrastructure de classe virtuelle et de vidéo;",
            "Resend — envoi de courriels transactionnels;",
            "Railway — hébergement d'application/d'infrastructure;",
            "Supabase — infrastructure de base de données.",
          ],
        },
        { type: "p", text: "Les fournisseurs de services ne reçoivent des renseignements que dans la mesure raisonnablement nécessaire à l'exécution des services pour lesquels FutureTutor retient leurs services, sous réserve des garanties contractuelles et légales applicables." },
      ],
    },
    {
      number: 33,
      heading: "Divulgations légales",
      blocks: [
        { type: "p", text: "FutureTutor peut divulguer des renseignements personnels lorsque la loi le permet ou l'exige, notamment lorsque cela est raisonnablement nécessaire pour :" },
        {
          type: "ul",
          items: [
            "se conformer à une ordonnance judiciaire;",
            "répondre à des demandes gouvernementales licites;",
            "enquêter sur une fraude;",
            "protéger des personnes contre un préjudice grave;",
            "protéger un mineur;",
            "répondre à des urgences;",
            "faire valoir des droits juridiques;",
            "enquêter sur une inconduite grave sur la Plateforme.",
          ],
        },
        { type: "p", text: "Lorsque cela est approprié et légalement permis, FutureTutor cherchera à limiter ces divulgations aux renseignements raisonnablement nécessaires." },
      ],
    },
    {
      number: 34,
      heading: "Transactions d'entreprise",
      blocks: [
        { type: "p", text: "Des renseignements personnels peuvent être divulgués dans le cadre :" },
        { type: "ul", items: ["d'un financement;", "d'un investissement;", "d'une réorganisation d'entreprise;", "d'une fusion;", "d'une acquisition;", "de la vente d'actifs commerciaux;", "d'une vérification diligente."] },
        { type: "p", text: "Lorsque la loi l'exige, des garanties appropriées et des restrictions de confidentialité s'appliqueront." },
      ],
    },
    {
      number: 35,
      heading: "Nous ne vendons pas les renseignements personnels comme produit de données",
      blocks: [
        { type: "p", text: "FutureTutor ne vend pas actuellement les renseignements personnels des Élèves, Parents, Tuteurs légaux ou Tuteurs à titre de produit commercial de données autonome." },
        { type: "p", text: "FutureTutor n'utilise pas actuellement les renseignements personnels des enfants à des fins de publicité comportementale." },
        { type: "p", text: "Si FutureTutor modifie de façon importante ces pratiques à l'avenir, nous mettrons à jour la présente Politique de confidentialité et obtiendrons le consentement requis." },
      ],
    },
    {
      number: 36,
      heading: "Communications transactionnelles",
      partTitle: "Partie X — Communications",
      blocks: [
        { type: "p", text: "FutureTutor peut envoyer des communications liées au service concernant :" },
        {
          type: "ul",
          items: ["la création de compte;", "la récupération de mot de passe;", "la sécurité;", "les Réservations;", "le jumelage de Tuteur;", "les paiements;", "les annulations;", "les remboursements;", "les invitations administratives;", "le statut du compte;", "les changements à la Plateforme;", "la sécurité;", "le soutien à la clientèle."],
        },
        { type: "p", text: "Les communications transactionnelles peuvent être nécessaires pour fournir la Plateforme et ne sont pas toujours facultatives." },
      ],
    },
    {
      number: 37,
      heading: "Communications de marketing",
      blocks: [
        { type: "p", text: "FutureTutor n'entend pas traiter les messages transactionnels essentiels comme des messages de marketing." },
        { type: "p", text: "Lorsque FutureTutor envoie des messages électroniques commerciaux à des fins de marketing, nous obtiendrons et gérerons le consentement conformément à la loi applicable et fournirons un mécanisme de désabonnement, lorsque requis." },
      ],
    },
    {
      number: 38,
      heading: "Témoins (cookies)",
      partTitle: "Partie XI — Témoins et technologies",
      blocks: [
        { type: "p", text: "FutureTutor peut utiliser des témoins, du stockage de navigateur, des identifiants de session ou des technologies similaires nécessaires pour :" },
        { type: "ul", items: ["authentifier les utilisateurs;", "maintenir les sessions;", "protéger les comptes;", "mémoriser les préférences;", "prendre en charge la sélection de la langue;", "assurer la sécurité;", "exploiter les fonctionnalités essentielles de la Plateforme."] },
        { type: "p", text: "FutureTutor peut fournir des renseignements supplémentaires dans une Politique sur les témoins distincte." },
      ],
    },
    {
      number: 39,
      heading: "Analytique",
      blocks: [
        { type: "p", text: "FutureTutor peut utiliser des renseignements techniques limités afin de comprendre la performance du système et de résoudre les problèmes de la Plateforme." },
        { type: "p", text: "Si FutureTutor introduit des technologies d'analytique, de publicité, de reciblage ou de suivi intersite supplémentaires, la présente Politique de confidentialité et la Politique sur les témoins seront mises à jour, lorsque requis." },
        { type: "p", text: "FutureTutor ne représente pas actuellement utiliser des services de publicité comportementale ou de reciblage, sauf s'ils sont expressément introduits." },
      ],
    },
    {
      number: 40,
      heading: "Renseignements recueillis automatiquement",
      partTitle: "Partie XII — Renseignements techniques",
      blocks: [
        { type: "p", text: "Lorsque les utilisateurs accèdent à FutureTutor, des systèmes techniques peuvent recueillir automatiquement des renseignements tels que :" },
        {
          type: "ul",
          items: [
            "l'adresse IP;",
            "le type de navigateur;",
            "le système d'exploitation;",
            "le type d'appareil;",
            "les horodatages de requête;",
            "les journaux d'application;",
            "les identifiants de session;",
            "les événements de sécurité;",
            "les événements d'authentification;",
            "les renseignements d'erreur;",
            "les renseignements de performance.",
          ],
        },
        { type: "p", text: "Ces renseignements peuvent constituer des renseignements personnels lorsqu'ils permettent d'identifier une personne ou de lui être associés." },
      ],
    },
    {
      number: 41,
      heading: "Fins des renseignements techniques",
      blocks: [
        { type: "p", text: "Les renseignements techniques peuvent être utilisés afin de :" },
        {
          type: "ul",
          items: ["exploiter la Plateforme;", "authentifier les utilisateurs;", "détecter les incidents de sécurité;", "prévenir la fraude;", "diagnostiquer les défaillances;", "maintenir la fiabilité;", "protéger les comptes;", "enquêter sur les mauvais usages;", "soutenir les utilisateurs."],
        },
      ],
    },
    {
      number: 42,
      heading: "Traitement à l'extérieur du Canada",
      partTitle: "Partie XIII — Traitement international",
      blocks: [
        { type: "p", text: "Certains fournisseurs de services de FutureTutor peuvent traiter ou stocker des renseignements personnels à l'extérieur du Canada." },
        {
          type: "p",
          text: "Par conséquent, les renseignements personnels peuvent être assujettis aux lois de la juridiction où ils sont traités et peuvent être accessibles aux tribunaux, aux forces de l'ordre ou aux autorités gouvernementales conformément à ces lois.",
        },
        { type: "p", text: "FutureTutor demeure responsable des renseignements personnels transférés à des fournisseurs de services dans la mesure requise par la loi canadienne applicable en matière de protection de la vie privée." },
        { type: "p", text: "Lorsque cela est approprié, FutureTutor utilise des mesures contractuelles ou organisationnelles conçues pour protéger les renseignements transférés." },
      ],
    },
    {
      number: 43,
      heading: "Durée de conservation des renseignements personnels",
      partTitle: "Partie XIV — Conservation",
      blocks: [
        { type: "p", text: "FutureTutor ne conserve les renseignements personnels que le temps raisonnablement nécessaire aux fins suivantes :" },
        {
          type: "ul",
          items: [
            "les fins décrites dans la présente Politique;",
            "le fonctionnement d'un compte actif;",
            "la prestation des services de tutorat;",
            "l'historique des transactions;",
            "le rapprochement des paiements;",
            "l'administration des versements aux Tuteurs;",
            "les exigences fiscales et comptables;",
            "le règlement des différends;",
            "les enquêtes de sécurité;",
            "la prévention de la fraude;",
            "les réclamations juridiques;",
            "les exigences réglementaires.",
          ],
        },
        { type: "p", text: "Différents types de renseignements peuvent avoir différentes périodes de conservation." },
      ],
    },
    {
      number: 44,
      heading: "Suppression du compte",
      blocks: [
        { type: "p", text: "Les utilisateurs peuvent demander la suppression de leur compte ou de leurs renseignements personnels en communiquant avec :" },
        { type: "p", text: "legal@futuretutor.ca" },
        { type: "p", text: "Les demandes de suppression sont assujetties aux renseignements que FutureTutor est autorisée ou tenue de conserver." },
        { type: "p", text: "Par exemple, nous pourrions devoir conserver certains :" },
        { type: "ul", items: ["dossiers financiers;", "dossiers fiscaux;", "dossiers de réservation;", "dossiers de prévention de la fraude;", "dossiers juridiques ou de différends;", "dossiers de sécurité;", "dossiers de consentement."] },
        { type: "p", text: "FutureTutor peut supprimer, anonymiser ou archiver de façon sécurisée les renseignements une fois que leur conservation n'est plus nécessaire." },
      ],
    },
    {
      number: 45,
      heading: "Conservation des renseignements des mineurs",
      blocks: [
        { type: "p", text: "FutureTutor entend faire preuve d'une prudence particulière à l'égard des renseignements concernant les mineurs." },
        { type: "p", text: "Les renseignements concernant un mineur ne devraient pas être conservés indéfiniment simplement parce que l'utilisateur a déjà été inscrit sur la Plateforme." },
        { type: "p", text: "Un conseiller juridique devrait valider le calendrier de conservation formel de FutureTutor avant un lancement public élargi." },
      ],
    },
    {
      number: 46,
      heading: "Mesures de sécurité",
      partTitle: "Partie XV — Sécurité",
      blocks: [
        { type: "p", text: "FutureTutor utilise des mesures de sécurité administratives, techniques et organisationnelles conçues pour protéger les renseignements personnels contre des risques tels que :" },
        { type: "ul", items: ["l'accès non autorisé;", "la divulgation non autorisée;", "la perte;", "le mauvais usage;", "l'altération;", "la destruction."] },
        { type: "p", text: "Les mesures de sécurité peuvent inclure :" },
        {
          type: "ul",
          items: [
            "des contrôles d'accès;",
            "l'authentification;",
            "le hachage des mots de passe;",
            "l'autorisation fondée sur les rôles;",
            "des opérations côté serveur protégées;",
            "des communications réseau chiffrées;",
            "des contrôles de gestion des secrets;",
            "un accès restreint aux renseignements d'adresse privés;",
            "la vérification de la signature des webhooks;",
            "des contrôles de base de données;",
            "la surveillance et la journalisation;",
            "des mesures de sécurité du fournisseur de paiement.",
          ],
        },
        { type: "p", text: "Aucun système n'est complètement sécurisé, et FutureTutor ne peut garantir une sécurité absolue." },
      ],
    },
    {
      number: 47,
      heading: "Contrôles d'accès",
      blocks: [
        { type: "p", text: "FutureTutor cherche à limiter l'accès aux renseignements personnels selon des rôles légitimes d'affaires et de Plateforme." },
        { type: "p", text: "Par exemple :" },
        {
          type: "ul",
          items: [
            "les Tuteurs potentiels ne devraient pas recevoir d'adresses privées exactes pendant le jumelage ouvert;",
            "les Tuteurs non liés ne devraient pas accéder aux renseignements de localisation privés d'une autre Réservation;",
            "les actions des Élèves gérés par un Tuteur légal peuvent être restreintes;",
            "l'accès administratif est contrôlé selon le rôle.",
          ],
        },
      ],
    },
    {
      number: 48,
      heading: "Sécurité des paiements",
      blocks: [
        { type: "p", text: "FutureTutor utilise des processeurs de paiement tiers afin de réduire la nécessité pour FutureTutor de traiter directement les renseignements complets de carte." },
        { type: "p", text: "FutureTutor n'entend pas stocker les numéros complets de carte de paiement lorsque Stripe ou un autre fournisseur conforme traite directement ces renseignements." },
      ],
    },
    {
      number: 49,
      heading: "Incidents de sécurité",
      partTitle: "Partie XVI — Atteintes à la vie privée",
      blocks: [
        { type: "p", text: "FutureTutor maintient des procédures destinées à identifier, évaluer, contenir et répondre aux incidents de confidentialité et de sécurité." },
        { type: "p", text: "Lorsqu'un incident touchant des renseignements personnels survient, FutureTutor peut :" },
        {
          type: "ul",
          items: ["enquêter sur l'incident;", "contenir l'incident;", "évaluer les renseignements touchés;", "évaluer le préjudice potentiel;", "aviser les personnes touchées;", "aviser les autorités de protection de la vie privée;", "conserver les dossiers d'incident requis;", "prendre des mesures correctives."],
        },
      ],
    },
    {
      number: 50,
      heading: "Avis en cas d'atteinte",
      blocks: [
        { type: "p", text: "Lorsque la loi applicable exige un avis ou un signalement, FutureTutor se conformera à ces exigences." },
        {
          type: "p",
          text: "En vertu de la LPRPDE, les organisations assujetties à la Loi doivent signaler certaines atteintes aux mesures de sécurité présentant un risque réel de préjudice grave et aviser les personnes touchées, tel que requis.",
        },
        { type: "p", text: "Différentes exigences provinciales peuvent également s'appliquer." },
      ],
    },
    {
      number: 51,
      heading: "Accès aux renseignements personnels",
      partTitle: "Partie XVII — Vos droits à la vie privée",
      blocks: [
        { type: "p", text: "Sous réserve de la loi applicable, les personnes peuvent demander l'accès aux renseignements personnels que FutureTutor détient à leur sujet." },
        { type: "p", text: "FutureTutor peut demander les renseignements raisonnablement nécessaires pour vérifier l'identité avant de fournir l'accès." },
        { type: "p", text: "Certaines exceptions peuvent s'appliquer, notamment les renseignements touchant :" },
        { type: "ul", items: ["la vie privée d'une autre personne;", "le secret professionnel de l'avocat;", "des renseignements commerciaux confidentiels;", "des restrictions légales;", "des préoccupations de sécurité."] },
      ],
    },
    {
      number: 52,
      heading: "Correction",
      blocks: [
        { type: "p", text: "Si des renseignements personnels détenus par FutureTutor sont inexacts ou incomplets, vous pouvez en demander la correction." },
        { type: "p", text: "Lorsque cela est approprié, FutureTutor corrigera ou annotera les renseignements." },
      ],
    },
    {
      number: 53,
      heading: "Retrait du consentement",
      blocks: [
        { type: "p", text: "Lorsque la loi le permet, vous pouvez demander le retrait du consentement pour un traitement futur." },
        { type: "p", text: "Voir la section 30." },
      ],
    },
    {
      number: 54,
      heading: "Suppression",
      blocks: [
        { type: "p", text: "Vous pouvez demander la suppression des renseignements personnels admissibles." },
        { type: "p", text: "FutureTutor évaluera les demandes sous réserve des exigences légales, transactionnelles, de sécurité et de conservation applicables." },
      ],
    },
    {
      number: 55,
      heading: "Portabilité des données et autres droits",
      blocks: [
        { type: "p", text: "Certaines juridictions peuvent prévoir des droits supplémentaires concernant :" },
        { type: "ul", items: ["la portabilité;", "la prise de décision automatisée;", "la divulgation;", "la correction;", "la désindexation;", "la cessation de la diffusion;", "le retrait du consentement."] },
        { type: "p", text: "FutureTutor répondra aux demandes valides conformément à la loi applicable." },
      ],
    },
    {
      number: 56,
      heading: "Résidents du Québec",
      partTitle: "Partie XVIII — Droits à la vie privée au Québec",
      blocks: [
        { type: "p", text: "Les résidents du Québec peuvent avoir des droits supplémentaires en vertu de la législation québécoise sur la protection des renseignements personnels." },
        { type: "p", text: "Sous réserve des exigences et exceptions applicables, ces droits peuvent inclure :" },
        {
          type: "ul",
          items: [
            "l'accès;",
            "la correction;",
            "le retrait du consentement;",
            "la cessation de la diffusion;",
            "la désindexation ou la réindexation, dans certaines circonstances;",
            "la portabilité, le cas échéant;",
            "les renseignements relatifs à la prise de décision automatisée, le cas échéant.",
          ],
        },
        { type: "p", text: "FutureTutor appliquera les protections obligatoires de la vie privée du Québec aux résidents québécois admissibles." },
      ],
    },
    {
      number: 57,
      heading: "Évaluations des facteurs relatifs à la vie privée",
      blocks: [
        { type: "p", text: "Lorsque la loi québécoise l'exige ou que cela est autrement approprié, FutureTutor peut mener des évaluations des facteurs relatifs à la vie privée pour des projets impliquant des renseignements personnels." },
        { type: "p", text: "Cela peut inclure l'évaluation des systèmes d'information, des fournisseurs de services, des changements technologiques ou des transferts de renseignements à l'extérieur du Québec, le cas échéant." },
      ],
    },
    {
      number: 58,
      heading: "Responsabilité de la protection des renseignements personnels au Québec",
      blocks: [
        {
          type: "p",
          text: "La personne exerçant la plus haute autorité au sein de FYRA SERVICES INC., ou une autre personne dûment déléguée, peut exercer les fonctions requises par la législation québécoise applicable en matière de protection des renseignements personnels.",
        },
        { type: "p", text: "Les demandes relatives à la protection des renseignements personnels peuvent être soumises à :" },
        { type: "p", text: "legal@futuretutor.ca" },
        { type: "p", text: "Cette clause devrait être validée par un conseiller juridique québécois avant le lancement public afin de s'assurer que la désignation formelle du responsable de la protection des renseignements personnels et les exigences de publication sont correctement mises en œuvre." },
      ],
    },
    {
      number: 59,
      heading: "Protection particulière des enfants",
      partTitle: "Partie XIX — Vie privée des enfants",
      blocks: [
        { type: "p", text: "FutureTutor reconnaît que les enfants et les jeunes constituent une population nécessitant une protection accrue de la vie privée." },
        { type: "p", text: "Nous cherchons à :" },
        {
          type: "ul",
          items: [
            "limiter la collecte aux renseignements raisonnablement nécessaires au tutorat;",
            "utiliser les renseignements à des fins compréhensibles et légitimes;",
            "éviter la publicité comportementale destinée aux enfants;",
            "recourir à l'autorisation du Parent ou Tuteur, lorsque cela est approprié;",
            "limiter la divulgation des adresses privées;",
            "protéger les renseignements des séances de tutorat;",
            "éviter la divulgation publique inutile;",
            "fournir des renseignements raisonnables sur la vie privée aux Parents et Tuteurs.",
          ],
        },
        { type: "p", text: "Les autorités canadiennes de protection de la vie privée ont de plus en plus mis l'accent sur la protection de la vie privée dès la conception et sur l'intérêt supérieur des enfants dans les environnements numériques et éducatifs." },
      ],
    },
    {
      number: 60,
      heading: "Enfants de moins de 13 ans",
      blocks: [
        { type: "p", text: "Un enfant de moins de 13 ans ne devrait pas créer ou exploiter de façon autonome un compte FutureTutor non restreint." },
        { type: "p", text: "FutureTutor exige la participation et le consentement appropriés d'un Parent ou Tuteur pour de tels utilisateurs, sauf lorsque la loi applicable permet une autre approche." },
        { type: "p", text: "Lorsque FutureTutor apprend que des renseignements personnels ont été recueillis auprès d'un enfant contrairement aux exigences de la Plateforme, nous pouvons :" },
        { type: "ul", items: ["suspendre le compte;", "demander l'autorisation d'un Parent ou Tuteur;", "restreindre les fonctionnalités;", "supprimer les renseignements, le cas échéant."] },
      ],
    },
    {
      number: 61,
      heading: "Demandes des Parents et Tuteurs",
      blocks: [
        { type: "p", text: "Un Parent ou Tuteur légal autorisé peut communiquer avec FutureTutor au sujet des renseignements associés à un enfant géré par un tuteur." },
        { type: "p", text: "FutureTutor peut vérifier l'identité et l'autorité avant de fournir l'accès ou d'apporter des modifications." },
        { type: "p", text: "FutureTutor peut également devoir tenir compte des intérêts du mineur en matière de vie privée, selon l'âge, la capacité, la loi applicable et les circonstances." },
      ],
    },
    {
      number: 62,
      heading: "Systèmes de jumelage et de cotation",
      partTitle: "Partie XX — Décisions automatisées et fondées sur des règles",
      blocks: [
        { type: "p", text: "FutureTutor utilise des logiciels et des règles afin de :" },
        {
          type: "ul",
          items: ["classer les Tuteurs;", "jumeler les demandes de tutorat;", "calculer les prix clients;", "déterminer les versements aux Tuteurs;", "maintenir les renseignements opérationnels sur la fiabilité;", "administrer les processus de la Plateforme."],
        },
        { type: "p", text: "Ces systèmes peuvent utiliser des renseignements personnels." },
        { type: "p", text: "FutureTutor n'utilise pas actuellement l'intelligence artificielle pour porter de façon indépendante des jugements scolaires généraux sur les Élèves." },
      ],
    },
    {
      number: 63,
      heading: "Cote de jumelage",
      blocks: [
        { type: "p", text: "FutureTutor peut calculer une cote de jumelage en utilisant des facteurs tels que :" },
        { type: "ul", items: ["l'admissibilité du Tuteur;", "la matière;", "le niveau scolaire;", "la disponibilité;", "le mode;", "la langue;", "les conflits d'horaire;", "les indicateurs de qualité;", "le lieu approximatif, le cas échéant."] },
        { type: "p", text: "Cette cote aide à déterminer quel Tuteur admissible reçoit une occasion." },
      ],
    },
    {
      number: 64,
      heading: "Tarification",
      blocks: [
        { type: "p", text: "FutureTutor peut calculer automatiquement la tarification client en utilisant des facteurs transactionnels." },
        { type: "p", text: "La cote de fiabilité de l'Élève n'est pas actuellement utilisée comme facteur direct de tarification." },
        { type: "p", text: "Les renseignements de tarification sont présentés avant que l'utilisateur ne s'engage envers une Réservation payante." },
      ],
    },
    {
      number: 65,
      heading: "Examen humain",
      blocks: [
        { type: "p", text: "Lorsque cela est approprié, FutureTutor peut permettre l'examen administratif ou la correction de certaines décisions ou de certains dossiers, notamment lorsque :" },
        { type: "ul", items: ["les renseignements sont inexacts;", "une fraude est soupçonnée;", "une erreur technique est survenue;", "un problème de sécurité existe;", "des circonstances exceptionnelles justifient un examen."] },
      ],
    },
    {
      number: 66,
      heading: "Services tiers",
      partTitle: "Partie XXI — Liens et services tiers",
      blocks: [
        { type: "p", text: "La Plateforme peut contenir des liens ou des intégrations impliquant des tiers." },
        { type: "p", text: "Les tiers ont leurs propres pratiques de confidentialité." },
        {
          type: "p",
          text: "La Politique de confidentialité de FutureTutor ne régit pas les renseignements recueillis de façon indépendante par une autre organisation lorsque cette organisation agit pour ses propres fins plutôt qu'à titre de fournisseur de services de FutureTutor.",
        },
        { type: "p", text: "Les utilisateurs devraient consulter les politiques pertinentes des tiers, le cas échéant." },
      ],
    },
    {
      number: 67,
      heading: "Mises à jour",
      partTitle: "Partie XXII — Modifications de la présente Politique",
      blocks: [
        { type: "p", text: "FutureTutor peut mettre à jour la présente Politique de confidentialité afin de refléter :" },
        { type: "ul", items: ["des changements à la Plateforme;", "de nouveaux services;", "des exigences légales;", "des pratiques de sécurité;", "des fournisseurs de services;", "des pratiques de confidentialité."] },
        { type: "p", text: "La date d'entrée en vigueur et la date de dernière mise à jour apparaîtront au haut de la Politique." },
        { type: "p", text: "Lorsque les modifications sont importantes, FutureTutor fournira un avis ou obtiendra le consentement requis par la loi." },
      ],
    },
    {
      number: 68,
      heading: "Coordonnées de FutureTutor",
      partTitle: "Partie XXIII — Coordonnées et plaintes",
      blocks: [
        { type: "p", text: "Les questions, demandes d'accès, demandes de correction, demandes de suppression ou autres demandes relatives à la protection des renseignements personnels peuvent être adressées à :" },
        { type: "p", text: "FutureTutor — détenu et exploité par FYRA SERVICES INC." },
        { type: "p", text: "FYRA SERVICES INC.\n8830 62e Ave NW\nEdmonton, Alberta T6E 0C8\nCanada" },
        { type: "p", text: "Confidentialité : legal@futuretutor.ca" },
        { type: "p", text: "Affaires juridiques : legal@futuretutor.ca" },
        { type: "p", text: "Site Web : futuretutor.ca" },
      ],
    },
    {
      number: 69,
      heading: "Plaintes",
      blocks: [
        { type: "p", text: "Si vous avez une préoccupation relative à la protection des renseignements personnels, nous vous encourageons à communiquer d'abord avec FutureTutor afin que nous puissions enquêter et vous répondre." },
        { type: "p", text: "Vous pouvez également avoir le droit de communiquer avec l'autorité de protection de la vie privée applicable, notamment, selon la juridiction :" },
        {
          type: "ul",
          items: [
            "le Commissariat à la protection de la vie privée du Canada;",
            "le Bureau du commissaire à l'information et à la protection de la vie privée de l'Alberta;",
            "la Commission d'accès à l'information du Québec;",
            "une autre autorité provinciale applicable en matière de protection de la vie privée.",
          ],
        },
      ],
    },
    {
      number: 70,
      heading: "Reconnaissance",
      partTitle: "Partie XXIV — Reconnaissance",
      blocks: [
        { type: "p", text: "En utilisant FutureTutor, vous reconnaissez avoir eu accès à la présente Politique de confidentialité." },
        { type: "p", text: "Lorsque le consentement est requis, FutureTutor le demandera par l'entremise du processus approprié de la Plateforme." },
        { type: "p", text: "Si vous êtes un Parent ou Tuteur légal fournissant un consentement au nom d'un mineur, vous déclarez détenir l'autorité nécessaire pour ce faire." },
      ],
    },
  ],
};
