import type { BookingStatus, TutoringMode } from "@/generated/prisma/enums";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { auth } from "@/lib/auth";
import { redirect, Link } from "@/i18n/navigation";
import { db } from "@/lib/db";
import { DashboardShell } from "@/components/dashboard/DashboardShell";
import { PageHeader } from "@/components/ui/PageHeader";
import { Badge } from "@/components/ui/Badge";
import { adminNavItems } from "@/lib/adminNav";

export default async function AdminBookingsPage({ params, searchParams }: { params: Promise<{ locale: string }>; searchParams: Promise<{ q?: string; status?: string; mode?: string }> }) {
  const { locale } = await params; const { q = "", status = "", mode = "" } = await searchParams; setRequestLocale(locale);
  const session = await auth(); const user = session?.user;
  if (!user || !["ADMIN", "SUPER_ADMIN"].includes(user.role)) { redirect({ href: "/login", locale }); return; }
  const [t, tNav, tSubjects] = await Promise.all([getTranslations({ locale, namespace: "admin.operations.bookings" }), getTranslations({ locale, namespace: "dashboard.nav" }), getTranslations({ locale, namespace: "subjects.items" })]);
  const statuses: BookingStatus[] = ["DRAFT", "PENDING_PAYMENT", "CONFIRMED", "CANCELLED", "COMPLETED"];
  const modes: TutoringMode[] = ["ONLINE", "IN_PERSON"];
  const bookings = await db.booking.findMany({ where: { ...(statuses.includes(status as BookingStatus) ? { status: status as BookingStatus } : {}), ...(modes.includes(mode as TutoringMode) ? { mode: mode as TutoringMode } : {}), ...(q ? { OR: [{ studentProfile: { is: { OR: [{ firstName: { contains: q, mode: "insensitive" } }, { lastName: { contains: q, mode: "insensitive" } }] } } }, { tutorProfile: { is: { user: { is: { name: { contains: q, mode: "insensitive" } } } } } }] } : {}) }, orderBy: { startAt: "desc" }, take: 100, select: { id: true, startAt: true, timezone: true, mode: true, status: true, subject: { select: { slug: true } }, studentProfile: { select: { firstName: true, lastName: true } }, tutorProfile: { select: { user: { select: { name: true } } } } } });
  return <DashboardShell navItems={await adminNavItems(tNav, user)} userName={user.name ?? ""}><PageHeader title={t("title")} description={t("description")} /><form className="mt-6 grid gap-3 rounded-xl border border-border bg-surface p-4 sm:grid-cols-4"><label className="text-sm font-bold">{t("search")}<input name="q" defaultValue={q} className="mt-1 h-11 w-full rounded-md border border-border px-3 font-normal" /></label><label className="text-sm font-bold">{t("status")}<select name="status" defaultValue={status} className="mt-1 h-11 w-full rounded-md border border-border px-3 font-normal"><option value="">{t("all")}</option>{statuses.map((value) => <option key={value}>{value}</option>)}</select></label><label className="text-sm font-bold">{t("mode")}<select name="mode" defaultValue={mode} className="mt-1 h-11 w-full rounded-md border border-border px-3 font-normal"><option value="">{t("all")}</option>{modes.map((value) => <option key={value}>{value}</option>)}</select></label><button className="min-h-11 self-end rounded-md bg-blue px-5 font-bold text-white">{t("apply")}</button></form>{bookings.length ? <div className="mt-6 space-y-3">{bookings.map((b) => <div key={b.id} className="rounded-xl border border-border bg-surface p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-extrabold text-navy">{tSubjects(b.subject.slug)}</h2><p className="mt-1 text-sm text-text-secondary">{b.studentProfile.firstName} {b.studentProfile.lastName} · {b.tutorProfile.user.name}</p></div><div className="flex gap-2"><Badge variant="neutral">{b.mode}</Badge><Badge variant="outline">{b.status}</Badge></div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-sm text-text-secondary"><span>{new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short", timeZone: b.timezone }).format(b.startAt)}</span><Link href={`/admin/bookings/${b.id}`} className="font-bold text-blue">{t("details")}</Link></div></div>)}</div> : <p className="mt-8 rounded-xl border border-dashed border-border p-8 text-center text-text-secondary">{t("empty")}</p>}</DashboardShell>;
}
